FROM python:3.11-slim

WORKDIR /app

COPY src/Blog.Processor.Python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/Blog.Processor.Python/app.py .

CMD ["python", "app.py"]
